import { useEffect, useState } from "react"
import { api } from "../api/client"
function toast(m,t){const e=document.createElement("div");e.style.cssText="position:fixed;top:20px;left:50%;transform:translateX(-50%);z-index:99999;padding:12px 28px;border-radius:10px;font-size:14px;box-shadow:0 4px 20px rgba(0,0,0,.5);pointer-events:none;transition:opacity .3s";e.style.background=t==="error"?"rgba(220,38,38,.9)":"rgba(16,8,12,.95)";e.style.border=t==="error"?"1px solid rgba(220,38,38,.3)":"1px solid rgba(168,85,247,.12)";e.style.color=t==="error"?"#ff7875":"#e0d0d0";e.textContent=m;document.body.appendChild(e);setTimeout(()=>{e.style.opacity="0";setTimeout(()=>e.remove(),300)},2500)}
export default function SmsPage(){
  const[list,setList]=useState([]),[loading,setLoading]=useState(true),[page,setPage]=useState(1),[pageSize,setPageSize]=useState(50),[total,setTotal]=useState(0),[search,setSearch]=useState(""),[err,setErr]=useState(""),[detail,setDetail]=useState(null)
  const load=async(p,ps,q)=>{setLoading(true);setErr("");const pp=p||page,pps=ps||pageSize,qq=q!==undefined?q:search;try{let url="/api/sms/notifications?page="+pp+"&pageSize="+pps;if(qq)url+="&deviceId="+encodeURIComponent(qq);const r=await api.request(url);const d=r.data||r;setList(d.list||d.data||d||[]);setTotal(d.total||0)}catch(e){setErr(e.message)}finally{setLoading(false)}}
  useEffect(()=>{load()},[])
  function searchNow(){setPage(1);load(1,pageSize,search)}
  function changePage(p){setPage(p);load(p,pageSize,search)}
  function changeSize(ps){setPageSize(ps);setPage(1);load(1,ps,search)}
  async function del(id){if(!confirm("确定删除这条短信?"))return;try{await api.request("/api/sms/notifications?id="+id,{method:"DELETE"});toast("已删除");load(page,pageSize,search)}catch(e){toast(e.message,"error")}}
  async function clearAll(){if(!confirm("确定清空所有短信?"))return;try{await api.request("/api/sms/notifications",{method:"DELETE"});toast("已清空");setPage(1);load(1,pageSize,"")}catch(e){toast(e.message,"error")}}
  const tp=Math.max(1,Math.ceil(total/pageSize))
  return<section className="panel" style={{display:"flex",flexDirection:"column",gap:14}}>
    <div className="panel-head"><h3 style={{margin:0,fontSize:18,fontWeight:600,color:"#ddd"}}>💬 短信中心</h3></div>
    <div className="rc-topbar" style={{padding:"10px 14px",margin:0}}>
      <div className="rc-top-left"><span style={{fontSize:14,color:"#8870a0"}}>设备ID</span><div className="rc-search"><input placeholder="输入设备ID搜索" value={search} onChange={e=>setSearch(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")searchNow()}}/><span onClick={searchNow}>🔍</span></div></div>
      <div className="rc-top-right"><button className="rc-btn" onClick={()=>{load(page,pageSize,search)}}>⟳ 刷新</button><button className="rc-btn" style={{background:"rgba(220,38,38,.1)",color:"#ff6b6b"}} onClick={clearAll}>清空全部</button></div>
    </div>
    {loading?<div style={{padding:40,textAlign:"center",color:"#8b949e",fontSize:14}}>加载中...</div>:err?<div className="toast err" style={{margin:16}}>{err}</div>:<div className="rc-table-wrap"><table className="rc-table" style={{fontSize:13}}><thead><tr><th style={{width:80}}>设备ID</th><th style={{width:140}}>发送号码</th><th>短信内容</th><th style={{width:160}}>时间</th><th style={{width:80}}>操作</th></tr></thead><tbody>{list.length===0?<tr><td colSpan={5} style={{textAlign:"center",padding:40,color:"#8b949e"}}>暂无短信记录</td></tr>:list.map((x,i)=><tr key={x.id||i}><td><span style={{color:"#1890ff",cursor:"pointer",textDecoration:"underline",fontFamily:"monospace",fontSize:12}} onClick={()=>{x.deviceId&&toast("跳转到设备: "+x.deviceId)}}>{x.deviceId||"-"}</span></td><td><span style={{fontFamily:"monospace",color:"#1890ff",fontSize:13}}>{x.address||x.number||x.sender||"-"}</span></td><td><div style={{maxWidth:400,overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap",cursor:"pointer",color:x.body?"#1677ff":void 0}} onClick={()=>{x.body&&setDetail(x)}} title={x.body||""}>{(x.body||x.content||x.message||"-").slice(0,200)}</div></td><td style={{fontSize:12,color:"#8870a0"}}>{x.date||x.time||x.created_at?new Date(x.date||x.time||x.created_at).toLocaleString():"-"}</td><td><button className="act-btn" style={{width:30,height:30,fontSize:14}} onClick={()=>del(x.id)} title="删除">🗑️</button></td></tr>)}</tbody></table></div>}
    {!loading&&!err&&<div className="rc-pagination"><span style={{fontSize:13,color:"#8870a0"}}>共 {total} 条</span><div style={{display:"flex",gap:4,alignItems:"center"}}><select value={pageSize} onChange={e=>changeSize(parseInt(e.target.value))} style={{background:"rgba(255,255,255,.04)",border:"1px solid rgba(168,85,247,.08)",borderRadius:6,color:"#b8a0c8",padding:"4px 8px",fontSize:12}}><option value={20}>20条/页</option><option value={50}>50条/页</option><option value={100}>100条/页</option><option value={200}>200条/页</option></select><button className="rc-btn" style={{padding:"4px 10px",fontSize:12}} disabled={page<=1} onClick={()=>changePage(page-1)}>上一页</button><span style={{fontSize:13,color:"#8870a0"}}>第 {page}/{tp} 页</span><button className="rc-btn" style={{padding:"4px 10px",fontSize:12}} disabled={page>=tp} onClick={()=>changePage(page+1)}>下一页</button></div></div>}
    {detail&&<div className="modal-overlay" onClick={()=>setDetail(null)}><div className="modal-box" style={{width:600}} onClick={e=>e.stopPropagation()}><div className="modal-head">📨 短信详情</div><div className="modal-body"><div style={{display:"grid",gridTemplateColumns:"80px 1fr",gap:"10px 14px",fontSize:14}}><span style={{color:"#8870a0"}}>设备ID</span><span style={{fontFamily:"monospace"}}>{detail.deviceId||"-"}</span><span style={{color:"#8870a0"}}>发送号码</span><span style={{color:"#1890ff",fontFamily:"monospace"}}>{detail.address||detail.number||detail.sender||"-"}</span><span style={{color:"#8870a0"}}>时间</span><span>{detail.date||detail.time||detail.created_at?new Date(detail.date||detail.time||detail.created_at).toLocaleString():"-"}</span><span style={{color:"#8870a0"}}>内容</span><span style={{wordBreak:"break-all",lineHeight:1.6,background:"rgba(255,255,255,.02)",borderRadius:8,padding:12,border:"1px solid rgba(168,85,247,.06)"}}>{detail.body||detail.content||detail.message||"-"}</span></div></div><div className="aaf-actions" style={{padding:"14px 20px",borderTop:"1px solid rgba(168,85,247,.06)"}}><button className="rc-btn" onClick={()=>setDetail(null)}>关闭</button></div></div></div>}
  </section>
}
